### PR TITLE
related contents changes

### PR DESCRIPTION
**Pull request by ashleyahn**
finished Florence Kelley and Historical Context tabs

### CODE REVIEW

**Comment by chrisdaaz** [comment]
hi @ashleyahn .. i can't merge this branch just yet. i'm getting errors when i run `hugo server` in the terminal. here's the error:

```
Error: Error building site: "C:\Users\cpd3149\Websites\florence-kelley\content\florence\1892.md:11:1": failed to unmarshal YAML: yaml: line 10: did not find expected key
```

this means that the YAML front-matter is not valid. in `\content\florence\1892.md` line 11.

please resolve these errors and commit the fixes to this branch.

here's some documentation on properly formatting lists in YAML: https://github.com/Animosity/CraftIRC/wiki/Complete-idiot's-introduction-to-yaml#lists

before committing your fixes, be sure to run `hugo server` in the terminal to make sure the website builds properly.

**Comment by chrisdaaz** [comment]
hi @ashleyahn i'm still getting build errors. I think there are YAML problems in multiple files. Refresh this branch, run `hugo server` in the terminal and resolve all of the YAML errors until the site builds properly. Commit the changes and let me know when it's ready to merge.

**Comment by ashleyahn** [comment]
Okay, I will take a look at that during my shift today. Thank you!

**Comment by ashleyahn** [comment]
I think I just accidentally merged. Could you take a look at it please?

**Comment by chrisdaaz** [comment]
i reverted your merge commit so this should be back to where it was @ashleyahn

**Comment by ashleyahn** [comment]
so is what I fixed is still saved? or were those changes lost?

**Comment by chrisdaaz** [comment]
oh, good point. they were not saved. i reverted the "revert merge commit" so now all of your changes are saved in the master branch. i think you should create a new branch from master and keep fixing the YAML errors. @ashleyahn

**Pull request merged**
